{%set name = "pandas-datareader" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # requirements.txt was no included in the sdist, use the GitHub archive until
  # fixed by upstream
  url: https://github.com/pydata/pandas-datareader/archive/v{{ version }}.tar.gz
  sha256: fb245e5752d93a124516697899c375f7d4f5491255b5b7e1e82085738b2c6035
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #sha256: 30eb46b0944b3bc8750d251907ee8166d5e259f1c103ea74867566664f8fdbe2

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"


requirements:
  host:
    - python
    - pip

  run:
    - python
    - pandas >=0.21
    - requests >=2.3.0
    - lxml

test:
  imports:
    - pandas_datareader

about:
  home: https://github.com/pydata/pandas-datareader
  license: BSD-3
  license_file: LICENSE.md
  license_family: BSD
  summary: 'Up to date remote data access for pandas, works for multiple versions of pandas'
  dev_url: https://github.com/pydata/pandas-datareader
  doc_url: https://pandas-datareader.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - mariusvniekerk
    - femtotrader
    - jreback
    - davidastephens
    - bashtage
