{%set name = "pandas-datareader" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7dee3fe6fa483c8c2ee4f1af91a65b542c5446d75a6fc25c832cad1ffca8ef0b

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - pandas >=0.19.2
    - requests >=2.3.0
    - wrapt
    - lxml

test:
  imports:
    - pandas_datareader
    - pandas_datareader.compat
    - pandas_datareader.google
    - pandas_datareader.iex
    - pandas_datareader.io
    - pandas_datareader.mstar
    - pandas_datareader.tests
    - pandas_datareader.tests.google
    - pandas_datareader.tests.io
    - pandas_datareader.tests.mstar
    - pandas_datareader.tests.yahoo
    - pandas_datareader.yahoo

about:
  home: https://github.com/pydata/pandas-datareader
  license: BSD-3
  license_file: LICENSE.md
  license_family: BSD
  summary: 'Up to date remote data access for pandas, works for multiple versions of pandas'
  dev_url: https://github.com/pydata/pandas-datareader
  doc_url: https://pandas-datareader.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - mariusvniekerk
    - femtotrader
    - jreback
    - davidastephens
    - bashtage
