travis:
  secure:
    BINSTAR_TOKEN: b97D03SpXGxFUb8EUZNUo2B6yyhG1BcYRP+DeEyyuKw3N04IcrDP+4KtMi1AFHp7rZDAvCQWCcXye2H5f6b5iDiN5x7AazVP4ZyPK5RxOMsWQZjQeZ6QcSz+Df/xwFsfoRWdxJu+QSrJ20nBQX0nmDICLjW2hpPZjysM2oO+nyjMvRmvh3YTD6PHZfa89ZeDJP5hzaEr8Ta2QipQwI43TJhKfqBAgznYdc/oX7h+ZjVaAZP0+fqVThustldwu3XngJRIr26oTkBME5Q74Pnc8VSvspXY3swBEJQad1kuZQYTY4ifiwVsUGg6KDd2+vSO3QnrGKKmMK86dFOrZvp+AdhAy37jpsb5HuX6Isw45Tl2+4N7bGMldvqUHWttvTTEqG0+i2grTCWIsfkNsGWrxUFpxH0QhiSNcC/l37O8AlgOM/JUhr11Sc+XSqgU2eM24BBBncg3jKa0CyF5j9mKhkyFiR4oliC1OogFdQ+cqMl/ZV31bSxaB0rvQ7+kVa6fqyVR1BnGj77xCGCTpd3ANLW1qjBErxt0z/omWpz7N9zdTm8NjdIdQ8nwR4Gh8iV19043nhJet8iE6HfaM1DX6hizdzzH8HSYkd5BoE5azVFqWTbjl2d3wMYmYMgX0xwKXtScoseUXfkEhUR5T1RsrbR+oj1N5ifZt0pTxhEQ6d0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
